/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collections = [
    {
      name: "repos",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE INDEX idx_repos_clone_status ON repos(clone_status)",
        "CREATE UNIQUE INDEX idx_repos_url_branch ON repos(repo_url, branch) WHERE branch IS NOT NULL",
        "CREATE UNIQUE INDEX idx_repos_local_path ON repos(local_path)",
        "CREATE INDEX idx_repos_source_path ON repos(source_path)",
      ],
      fields: [
        { name: "repo_url", type: "text", required: false, max: 2048 },
        { name: "local_path", type: "text", required: true, max: 1024 },
        { name: "source_path", type: "text", required: false, max: 2048 },
        { name: "branch", type: "text", required: false, max: 256 },
        { name: "default_branch", type: "text", required: false, max: 256 },
        { name: "clone_status", type: "text", required: true, max: 32 },
        { name: "cloned_at", type: "number", required: true },
        { name: "last_pulled", type: "number", required: false },
        { name: "last_accessed_at", type: "number", required: false },
        { name: "opencode_config_name", type: "text", required: false, max: 256 },
        { name: "is_worktree", type: "bool", required: false },
        { name: "is_local", type: "bool", required: false },
      ],
    },
    {
      name: "user_preferences",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE UNIQUE INDEX idx_user_preferences_user_id ON user_preferences(user_id)",
      ],
      fields: [
        { name: "user_id", type: "text", required: true, max: 128 },
        { name: "preferences", type: "json", required: true },
        { name: "updated_at", type: "number", required: true },
      ],
    },
    {
      name: "opencode_configs",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE UNIQUE INDEX idx_opencode_configs_user_name ON opencode_configs(user_id, config_name)",
        "CREATE INDEX idx_opencode_configs_default ON opencode_configs(user_id, is_default)",
      ],
      fields: [
        { name: "user_id", type: "text", required: true, max: 128 },
        { name: "config_name", type: "text", required: true, max: 256 },
        { name: "config_content", type: "text", required: true },
        { name: "is_default", type: "bool", required: false },
        { name: "created_at", type: "number", required: true },
        { name: "updated_at", type: "number", required: true },
      ],
    },
    {
      name: "repo_settings",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE UNIQUE INDEX idx_repo_settings_repo_key ON repo_settings(repo_id, key)",
      ],
      fields: [
        { name: "repo_id", type: "text", required: true, max: 128 },
        { name: "key", type: "text", required: true, max: 256 },
        { name: "value", type: "text", required: true },
        { name: "updated_at", type: "number", required: true },
      ],
    },
    {
      name: "trusted_ssh_hosts",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE UNIQUE INDEX idx_trusted_ssh_hosts_host ON trusted_ssh_hosts(host)",
      ],
      fields: [
        { name: "host", type: "text", required: true, max: 512 },
        { name: "key_type", type: "text", required: true, max: 64 },
        { name: "public_key", type: "text", required: true },
        { name: "created_at", type: "number", required: true },
        { name: "updated_at", type: "number", required: true },
      ],
    },
    {
      name: "automation_jobs",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE INDEX idx_automation_jobs_repo ON automation_jobs(repo_id)",
        "CREATE INDEX idx_automation_jobs_next_run ON automation_jobs(enabled, next_run_at)",
      ],
      fields: [
        { name: "repo_id", type: "text", required: true, max: 128 },
        { name: "name", type: "text", required: true, max: 256 },
        { name: "description", type: "text", required: false },
        { name: "enabled", type: "bool", required: false },
        { name: "automation_mode", type: "text", required: false, max: 32 },
        { name: "interval_minutes", type: "number", required: false },
        { name: "cron_expression", type: "text", required: false, max: 128 },
        { name: "timezone", type: "text", required: false, max: 64 },
        { name: "agent_slug", type: "text", required: false, max: 128 },
        { name: "prompt", type: "text", required: true },
        { name: "model", type: "text", required: false, max: 256 },
        { name: "skill_metadata", type: "json", required: false },
        { name: "created_at", type: "number", required: true },
        { name: "updated_at", type: "number", required: true },
        { name: "last_run_at", type: "number", required: false },
        { name: "next_run_at", type: "number", required: false },
      ],
    },
    {
      name: "automation_runs",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE INDEX idx_automation_runs_job ON automation_runs(job_id, started_at DESC)",
        "CREATE INDEX idx_automation_runs_repo ON automation_runs(repo_id, started_at DESC)",
      ],
      fields: [
        { name: "job_id", type: "text", required: true, max: 128 },
        { name: "repo_id", type: "text", required: true, max: 128 },
        { name: "trigger_source", type: "text", required: true, max: 32 },
        { name: "status", type: "text", required: true, max: 32 },
        { name: "started_at", type: "number", required: true },
        { name: "finished_at", type: "number", required: false },
        { name: "created_at", type: "number", required: true },
        { name: "session_id", type: "text", required: false, max: 256 },
        { name: "session_title", type: "text", required: false },
        { name: "log_text", type: "text", required: false },
        { name: "response_text", type: "text", required: false },
        { name: "error_text", type: "text", required: false },
      ],
    },
    {
      name: "prompt_templates",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [],
      fields: [
        { name: "title", type: "text", required: true, max: 256 },
        { name: "category", type: "text", required: true, max: 64 },
        { name: "cadence_hint", type: "text", required: true, max: 64 },
        { name: "suggested_name", type: "text", required: true, max: 256 },
        { name: "suggested_description", type: "text", required: false },
        { name: "description", type: "text", required: false },
        { name: "prompt", type: "text", required: true },
        { name: "created_at", type: "number", required: true },
        { name: "updated_at", type: "number", required: true },
      ],
    },
    {
      name: "opencode_model_state",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE UNIQUE INDEX idx_opencode_model_state_user ON opencode_model_state(user_id)",
      ],
      fields: [
        { name: "user_id", type: "text", required: true, max: 128 },
        { name: "recent", type: "json", required: true },
        { name: "favorite", type: "json", required: true },
        { name: "variant", type: "json", required: true },
        { name: "updated_at", type: "number", required: true },
      ],
    },
    {
      name: "app_secrets",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE UNIQUE INDEX idx_app_secrets_key ON app_secrets(key)",
      ],
      fields: [
        { name: "key", type: "text", required: true, max: 256 },
        { name: "value", type: "text", required: true },
        { name: "created_at", type: "number", required: true },
        { name: "updated_at", type: "number", required: true },
      ],
    },
    {
      name: "push_subscriptions",
      type: "base",
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      indexes: [
        "CREATE UNIQUE INDEX idx_push_sub_endpoint ON push_subscriptions(endpoint)",
        "CREATE INDEX idx_push_sub_user ON push_subscriptions(user_id)",
      ],
      fields: [
        { name: "user_id", type: "text", required: true, max: 128 },
        { name: "endpoint", type: "text", required: true },
        { name: "p256dh", type: "text", required: true },
        { name: "auth", type: "text", required: true },
        { name: "device_name", type: "text", required: false, max: 256 },
        { name: "created_at", type: "number", required: true },
        { name: "last_used_at", type: "number", required: false },
      ],
    },
  ];

  return app.importCollections(collections, false);
}, (app) => {
  return null;
});
